services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: expense-app-homem-maquina
    volumes:
      - ./expense-app:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
      # - "${APP_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - expense-app-homem-maquina-network

  mariadb:
    image: mariadb:latest
    volumes:
      - ./docker/dump:/docker-entrypoint-initdb.d
      - mariadb_data:/var/lib/mysql
    ports:
      - "33:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_expense_app_homem_maquina
      MYSQL_USER: db
      MYSQL_PASSWORD: password
      # MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      # MYSQL_DATABASE: $DB_DATABASE
      # MYSQL_USER: $DB_USERNAME
      # MYSQL_PASSWORD: $DB_PASSWORD
    networks:
      - expense-app-homem-maquina-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - "8090:80"
      # - "${PHP_MY_ADMIN_PORT}:80"
    environment:
      PMA_HOST: mariadb
      # MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - expense-app-homem-maquina-network

networks:
  expense-app-homem-maquina-network:
    driver: bridge

volumes:
  mariadb_data: